fix IMSTMAP is not an ObservableMap
mobxjs/mobx-state-tree pull request #1570
Opened 2020-08-24 08:22 UTC by MoonBall

fix https://github.com/mobxjs/mobx/issues/2422#issuecomment-674816446.

I don't know how to add test for ts type.

2020-09-01 02:49 UTC, MoonBall commented
@mweststrate PTAL

2020-09-01 07:34 UTC, mweststrate commented
Sorry focusing on mobx 6 first. If someone else can review that'd be great

Op di 1 sep. 2020 03:50 schreef Gang Chen <notifications@github.com>:

> @mweststrate <https://github.com/mweststrate> PTAL
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mobxjs/mobx-state-tree/pull/1570#issuecomment-684161770>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN4NBDGBLTQGZRSGCU3XO3SDROOJANCNFSM4QJHQO4A>
> .
>

2020-10-22 21:20 UTC, jesse-savary requested changes
Pulled this down and tested it but unfortunately I don't think this solves the problem.

The following test fails:
```
const todoListValues = values(store.todos)
todoListValues.forEach((it) => {
  type doTest = AssertTrue<Has<typeof it, { id: number; text: string }>> |
    AssertFalse<IsAny<typeof it>>
})
```

Somehow `it` is being typed to any. I don't have time to dig deeper but @MoonBall I figured you'd want to chime in. Is this some kind of error on my end?

2020-12-14 08:04 UTC, MoonBall commented
Sorry for my late reply.
I rebased master, and there is an error as below.
![image](https://user-images.githubusercontent.com/13298548/102054692-b7e64b80-3e24-11eb-8fbb-d06752da4730.png)

The reason is the return value of `IMSTMap`'s `toJSON()` method is an object rather than an array that is the return value of `ObservableMap`'s `toJSON()` method. So `IMSTMap` is not incompatible with `ObservableMap`. 

Now my commit is out-of-date, I think there is no simple way to fix it 😰.

2020-12-18 20:03 UTC, jamonholmgren commented
If someone has a better idea to fix this, feel free to open a new PR or comment here with ideas. In the meantime, I'm going to close this. Thanks for your work on this, @MoonBall !

2020-12-18 20:03 UTC, closed without merging