docs: Add link to mst-query
mobxjs/mobx-state-tree pull request #1727
Opened 2021-06-17 14:08 UTC by k-ode

@jamonholmgren suggested I add a link to mst-query (a query library for mobx-state-tree) to the docs. I didn't see any lists for addons or libraries so I added one in the resources file.

2021-06-18 20:59 UTC, jamonholmgren requested changes
Feel free to update my wording, but I made a stab at it.

2021-06-18 20:59 UTC, jamonholmgren commented on docs/tips/resources.md
> +- [mst-query](https://github.com/ConrabOpto/mst-query/)
Let's add some context!

```suggestion
- [mst-query](https://github.com/ConrabOpto/mst-query/) - Query library for MST with support for auto normalization, garbage collection, infinite scroll & pagination, and more
```

2021-06-20 20:36 UTC, k-ode commented
@jamonholmgren Updated, thanks!

2021-06-30 00:07 UTC, jamonholmgren approved these changes

2021-06-30 00:07 UTC, merged

2021-06-30 00:08 UTC, jamonholmgren commented
Thank you @k-ode !